#version: '3.8'

services:
  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: pemilos_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
    networks:
      - pemilos

  # PHP-FPM
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: pemilos_php
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - mysql
      - redis
    networks:
      - pemilos
    environment:
      - DB_HOST=mysql
      - REDIS_HOST=redis

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: pemilos_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: pemilos
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: pemilos
      MYSQL_PASSWORD: pemilos_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - pemilos
    command: --default-authentication-plugin=mysql_native_password

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: pemilos_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - pemilos

  # Queue Worker (multiple workers untuk handle load)
  queue-worker:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
      - redis
    networks:
      - pemilos
    command: php artisan queue:work --sleep=3 --tries=3 --max-time=3600
    deploy:
      replicas: 2

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  pemilos:
    driver: bridge
